# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\QT_UI\Master_Client\master_client.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Master_Client(object):
    def setupUi(self, Master_Client):
        Master_Client.setObjectName("Master_Client")
        Master_Client.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Master_Client.sizePolicy().hasHeightForWidth())
        Master_Client.setSizePolicy(sizePolicy)
        Master_Client.setMinimumSize(QtCore.QSize(1024, 700))
        self.centralWidget = QtWidgets.QWidget(Master_Client)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollerFrame = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollerFrame.sizePolicy().hasHeightForWidth())
        self.scrollerFrame.setSizePolicy(sizePolicy)
        self.scrollerFrame.setMinimumSize(QtCore.QSize(400, 400))
        self.scrollerFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollerFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollerFrame.setObjectName("scrollerFrame")
        self.scrollArea1 = QtWidgets.QScrollArea(self.scrollerFrame)
        self.scrollArea1.setGeometry(QtCore.QRect(0, 0, 691, 611))
        self.scrollArea1.setWidgetResizable(True)
        self.scrollArea1.setObjectName("scrollArea1")
        self.galaxyMapFrame = QtWidgets.QWidget()
        self.galaxyMapFrame.setGeometry(QtCore.QRect(0, 0, 689, 609))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.galaxyMapFrame.sizePolicy().hasHeightForWidth())
        self.galaxyMapFrame.setSizePolicy(sizePolicy)
        self.galaxyMapFrame.setMinimumSize(QtCore.QSize(400, 400))
        self.galaxyMapFrame.setObjectName("galaxyMapFrame")
        self.scrollArea1.setWidget(self.galaxyMapFrame)
        self.horizontalLayout.addWidget(self.scrollerFrame)
        self.infoPanelFrame = QtWidgets.QFrame(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.infoPanelFrame.sizePolicy().hasHeightForWidth())
        self.infoPanelFrame.setSizePolicy(sizePolicy)
        self.infoPanelFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.infoPanelFrame.setMaximumSize(QtCore.QSize(16777210, 16777210))
        self.infoPanelFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.infoPanelFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.infoPanelFrame.setMidLineWidth(0)
        self.infoPanelFrame.setObjectName("infoPanelFrame")
        self.horizontalLayout.addWidget(self.infoPanelFrame)
        self.infoPanelFrame.raise_()
        self.scrollerFrame.raise_()
        Master_Client.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Master_Client)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuServer = QtWidgets.QMenu(self.menuBar)
        self.menuServer.setObjectName("menuServer")
        self.menuMain = QtWidgets.QMenu(self.menuBar)
        self.menuMain.setObjectName("menuMain")
        Master_Client.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(Master_Client)
        self.mainToolBar.setObjectName("mainToolBar")
        Master_Client.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(Master_Client)
        self.statusBar.setObjectName("statusBar")
        Master_Client.setStatusBar(self.statusBar)
        self.actionPull_from_server = QtWidgets.QAction(Master_Client)
        self.actionPull_from_server.setObjectName("actionPull_from_server")
        self.actionPush_to_server = QtWidgets.QAction(Master_Client)
        self.actionPush_to_server.setObjectName("actionPush_to_server")
        self.actionConnect_to_server = QtWidgets.QAction(Master_Client)
        self.actionConnect_to_server.setObjectName("actionConnect_to_server")
        self.actionDisconnect_from_server = QtWidgets.QAction(Master_Client)
        self.actionDisconnect_from_server.setObjectName("actionDisconnect_from_server")
        self.actionQuit_client = QtWidgets.QAction(Master_Client)
        self.actionQuit_client.setObjectName("actionQuit_client")
        self.menuServer.addAction(self.actionConnect_to_server)
        self.menuServer.addAction(self.actionDisconnect_from_server)
        self.menuServer.addSeparator()
        self.menuServer.addAction(self.actionPull_from_server)
        self.menuServer.addAction(self.actionPush_to_server)
        self.menuMain.addAction(self.actionQuit_client)
        self.menuBar.addAction(self.menuMain.menuAction())
        self.menuBar.addAction(self.menuServer.menuAction())

        self.retranslateUi(Master_Client)
        QtCore.QMetaObject.connectSlotsByName(Master_Client)

    def retranslateUi(self, Master_Client):
        _translate = QtCore.QCoreApplication.translate
        Master_Client.setWindowTitle(_translate("Master_Client", "Simple Galaxy Viewer"))
        self.menuServer.setTitle(_translate("Master_Client", "Server"))
        self.menuMain.setTitle(_translate("Master_Client", "Main"))
        self.actionPull_from_server.setText(_translate("Master_Client", "Pull from server"))
        self.actionPush_to_server.setText(_translate("Master_Client", "Push to server"))
        self.actionConnect_to_server.setText(_translate("Master_Client", "Connect to server"))
        self.actionDisconnect_from_server.setText(_translate("Master_Client", "Disconnect from server"))
        self.actionQuit_client.setText(_translate("Master_Client", "Quit client"))

